//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalAdoptionSystem.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PETADOPTIONEntities : DbContext
    {
        public PETADOPTIONEntities()
            : base("name=PETADOPTIONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADOPTION> ADOPTIONs { get; set; }
        public virtual DbSet<AUDIT> AUDITs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<EUTHANASIA> EUTHANASIAs { get; set; }
        public virtual DbSet<PET> PETs { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
        public virtual DbSet<USERGROUP> USERGROUPs { get; set; }
    }
}
